# Generated by Django 2.0.3 on 2019-09-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_extendeduser_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='phone_num',
            new_name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='age',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='dateOfBirth',
            field=models.DateField(default='2013-03-12'),
            preserve_default=False,
        ),
    ]
