# Generated by Django 2.0.3 on 2019-09-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190906_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='profileImage',
            field=models.ImageField(default='media/profileImage.jpg', upload_to='media/'),
        ),
    ]
